# Stage 1: Build Stage

# Use the node image from official Docker Hub
FROM node as build-stage
# Set the working directory
WORKDIR /app
# Copy the package files in the container
COPY package*.json ./
# Install the project dependecies
RUN npm install
# Copy the rest of the project files to the container
COPY . .
# Build the Vue.js application into dist folder
RUN npm run build

# Stage 2: Production Stage

# use the lighweight Nignx image from the previus state to the nginx container
FROM nginx as production-stage
# Copy the build application from the previos state to the Nginx container
COPY --from=build-stage /app/dist /usr/share/nginx/html
# Copy the nginx configuration file
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
# Expose the port
EXPOSE 5173
# start nginx application
CMD ["nginx", "-g", "daemon off;"]
